# Generated by Django 5.0.2 on 2024-03-05 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_products_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Small', models.IntegerField(default=None)),
                ('Medium', models.IntegerField(default=None)),
                ('Large', models.IntegerField(default=None)),
                ('Extra_Large', models.IntegerField(default=None)),
                ('Total_Stock', models.IntegerField(default=None)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
        ),
    ]
