# Generated by Django 5.0.2 on 2024-03-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
