# Generated by Django 5.0.2 on 2024-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_extra_large_stock_extra_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Total_stock',
            field=models.IntegerField(default=None),
        ),
    ]
