# Generated by Django 5.0.2 on 2024-03-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_total_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Total_stock',
        ),
    ]
