# Generated by Django 5.0.2 on 2024-03-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
