# Generated by Django 5.0 on 2024-04-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stock_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
