# Generated by Django 5.0.2 on 2024-03-04 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
