# Generated by Django 5.0.2 on 2024-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_offer_products_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
