# Generated by Django 5.0.2 on 2024-03-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_code',
        ),
    ]
