# Generated by Django 5.0.2 on 2024-03-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_name_products_name_and_more'),
        ('stock', '0007_alter_stock_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
