# Generated by Django 5.0.2 on 2024-03-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_code_id_products_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cod',
            new_name='code',
        ),
    ]
