# Generated by Django 5.0.2 on 2024-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_cod_products_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
