# Generated by Django 5.0.2 on 2024-03-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_image_products_image1_products_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
