# Generated by Django 5.0 on 2024-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_products_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Large',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='Small',
            field=models.IntegerField(default=0),
        ),
    ]
