# Generated by Django 5.0 on 2024-04-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_products_large_products_medium_products_small'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Large',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Medium',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Small',
            new_name='small',
        ),
    ]
