# Generated by Django 5.0 on 2024-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_large_products_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='large',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='medium',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='small',
            field=models.IntegerField(default=None),
        ),
    ]
