# Generated by Django 5.0.2 on 2024-03-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_reference_coupon_reference'),
        ('user', '0005_alter_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_coupon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userdata'),
            preserve_default=False,
        ),
    ]
