# Generated by Django 5.0.2 on 2024-03-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_reference_coupon_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='coupon',
            new_name='reference_code',
        ),
    ]
