# Generated by Django 5.0.2 on 2024-03-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_rename_coupon_reference_reference_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_coupon',
            old_name='coupon_code',
            new_name='reference_coupon_code',
        ),
    ]
