# Generated by Django 5.0 on 2024-04-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_rename_coupon_code_reference_coupon_reference_coupon_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
