# Generated by Django 5.0.2 on 2024-03-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_locality',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=15),
        ),
    ]
