# Generated by Django 5.0.2 on 2024-03-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_list_order_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
