# Generated by Django 5.0.2 on 2024-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_user_delete_checkout_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order_list',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
