# Generated by Django 5.0.2 on 2024-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_list_coupon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
