# Generated by Django 5.0.2 on 2024-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
