# Generated by Django 5.0.2 on 2024-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_list_price_alter_order_list_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='coupon_price',
            field=models.IntegerField(default=None),
        ),
    ]
