# Generated by Django 5.0.2 on 2024-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_order_list_image_order_list_coupon_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='coupon_price',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='quantity',
        ),
    ]
