# Generated by Django 5.0.2 on 2024-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_order_list_coupon_price_order_list_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='coupon_price',
        ),
        migrations.RemoveField(
            model_name='order_list',
            name='image',
        ),
        migrations.AddField(
            model_name='order_list',
            name='coupon',
            field=models.CharField(default='No Coupon', max_length=15),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
