# Generated by Django 5.0.2 on 2024-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_remove_order_list_price_remove_order_list_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='category_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='offer',
            field=models.IntegerField(default=None),
        ),
    ]
