# Generated by Django 5.0.2 on 2024-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_orderproduct_category_info_orderproduct_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='offer',
            field=models.CharField(default='No offer', max_length=15),
        ),
    ]
