# Generated by Django 5.0.2 on 2024-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_order_list_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
