# Generated by Django 5.0 on 2024-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_order_list_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='selected_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
