# Generated by Django 5.0 on 2024-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_orderproduct_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
