# Generated by Django 5.0 on 2024-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_order_list_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='current_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
