# Generated by Django 5.0.2 on 2024-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Refund', 'Refund'), ('Bonuspoint', 'Bonus point')], max_length=10),
        ),
    ]
