# Generated by Django 5.0.2 on 2024-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitms'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
